export const GET_PREMISSION = 'GET_PREMISSION';
export const SET_RECEIPTS = 'SET_RECEIPTS';
export const ERROR_HANDLER = 'ERROR_HANDLER';
export const SEE_RECIPT_DETAIL = 'SEE_RECIPT_DETAIL';
export const SET_FAVOURITES = 'SET_FAVOURITES';
export const UPDATE_FAVOURITIES = 'UPDATE_FAVOURITIES';
// export const REMOVE_FROM_FAVOURITIES = 'REMOVE_FROM_FAVOURITIES';