export const GET_PREMISSION = 'GET_PREMISSION';
export const SET_RECEIPTS = 'SET_RECEIPTS';
export const ERROR_HANDLER = 'ERROR_HANDLER';
export const SEE_RECIPT_DETAIL = 'SEE_RECIPT_DETAIL';
export const SET_FAVOURITES = 'SET_FAVOURITES';
export const UPDATE_FAVOURITIES = 'UPDATE_FAVOURITIES';
export const ADD_PURCHASE_LIST = 'ADD_PURCHASE_LIST';
export const REMOVE_FROM_PURCHASE_LIST = 'REMOVE_FROM_PURCHASE_LIST';
